/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sanitized.glb')
  console.log(nodes);
  console.log(materials);
  materials.Materiale.wireframe = true;
  materials.Materiale.color.r = 0;
  materials.Materiale.color.g = 0;
  materials.Materiale.color.b = 0;
  
  return (
    <group {...props} dispose={null}>
      <mesh scale={[0.11,0.11,0.11]} geometry={nodes.Poltronciona.geometry} material={materials.Materiale} rotation={[Math.PI / 25, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/poltrona.glb')
